/**
 *
 * @author Schubert Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Schubert System </br>
 * Schubert system Copyright - NewPortBay LLC copy_right_range</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

app.controller("Landing_page", [ '$scope', '$rootScope', '$location', '$window', '$q', '$http',
				    function( $scope, $rootScope, $location, $window, $q, $http) {

		$scope.People_test = {
		_Id: '',
		_First_name : '', 
		_Last_name : '', 
		_Organization_id : ''
		};




		$scope.$on('$viewContentLoaded', function(event) {
			var biggestHeight = 0;
			var height = 0;
			$(".main").find('*').each(function(){
				height = $(this).position().top + $(this).height() + 100;
				if (height > biggestHeight ) {
					biggestHeight = height;
				}
			});
			$(".main").height(biggestHeight);
		});

}]);


